USE ABC_B


select * FROM CONSIGNMENT
SELECT * FROM CUSTOMER
SELECT * FROM DELIVERY_PRICE
SELECT * FROM DELIVERY_TYPE
SELECT * FROM DISTRICT
SELECT * FROM EMPLOYEE
SELECT * FROM PARCEL_OF_CONSIGNMENT
SELECT * FROM STATUS

SELECT * FROM WEEKLY_DISTRICT_DIVISION
select * from CONSIGNMENT
ORDER BY SCHEDULED_PICKUP_TIME ASC

SELECT * FROM DELIVERY_PRICE
SELECT * FROM PARCEL_OF_CONSIGNMENT

select * FROM CONSIGNMENT
SELECT * FROM EMPLOYEE
SELECT * FROM PARCEL_OF_CONSIGNMENT
SELECT * FROM DELIVERY_PRICE

USE ABC_B
select * from PARCEL_OF_CONSIGNMENT
JOiN CONSIGNMENT  ON PARCEL_OF_CONSIGNMENT.CONSIGNMENT = CONSIGNMENT.CONSIGNMENT_NR
JOIN EMPLOYEE  ON PARCEL_OF_CONSIGNMENT.BIKER = EMPLOYEE.EMPLOYEENR
-- WHERE BIKER = 8
WHERE BIKER = 7 OR BIKER = 8
ORDER BY DELIVERY_TIME ASC




USE anbc_ster
SELECT * FROM CONSIGNMENT_FACT
SELECT * FROM PERSONEEL_DIM
SELECT * FROM TIME_DIM
SELECT * FROM WEATHER_DIM

USE anbc_ster
SELECT * FROM CONSIGNMENT_FACT
INNER JOIN PERSONEEL_DIM ON CONSIGNMENT_FACT.PERSONEEL_ID = PERSONEEL_DIM.PERSONEEL_ID
INNER JOIN TIME_DIM ON CONSIGNMENT_FACT.SCHED_TIME_ID = TIME_DIM.TIME_ID
INNER JOIN WEATHER_DIM ON CONSIGNMENT_FACT.WEATHER_ID = WEATHER_DIM.WEATHER_ID
--where PERSONEEL_DIM.PERSONEEL_ID = 7 OR PERSONEEL_DIM.PERSONEEL_ID = 8
ORDER BY TIME_DIM.DATUM ASC


USE anbc_ster
SELECT SUM(AANTAL) as telaat
FROM CONSIGNMENT_FACT
INNER JOIN PERSONEEL_DIM ON CONSIGNMENT_FACT.PERSONEEL_ID = PERSONEEL_DIM.PERSONEEL_ID
INNER JOIN TIME_DIM ON CONSIGNMENT_FACT.PICKUP_TIME_ID = TIME_DIM.TIME_ID
INNER JOIN TIME_DIM SCH ON CONSIGNMENT_FACT.SCHED_TIME_ID = SCH.TIME_ID
INNER JOIN WEATHER_DIM ON CONSIGNMENT_FACT.WEATHER_ID = WEATHER_DIM.WEATHER_ID
where SCH.DATUM < TIME_DIM.DATUM 
AND PERSONEEL_DIM.EXPRESS_ERVARING = 1

USE anbc_ster
SELECT SUM(AANTAL) as OPTIJD
FROM CONSIGNMENT_FACT
INNER JOIN PERSONEEL_DIM ON CONSIGNMENT_FACT.PERSONEEL_ID = PERSONEEL_DIM.PERSONEEL_ID
INNER JOIN TIME_DIM ON CONSIGNMENT_FACT.PICKUP_TIME_ID = TIME_DIM.TIME_ID
INNER JOIN TIME_DIM SCH ON CONSIGNMENT_FACT.SCHED_TIME_ID = SCH.TIME_ID
INNER JOIN WEATHER_DIM ON CONSIGNMENT_FACT.WEATHER_ID = WEATHER_DIM.WEATHER_ID
where SCH.DATUM >= TIME_DIM.DATUM 
AND PERSONEEL_DIM.EXPRESS_ERVARING = 1




USE anbc_ster
SELECT SUM(AANTAL) as aantalBezorgingenbijslechtweer
FROM CONSIGNMENT_FACT
INNER JOIN PERSONEEL_DIM ON CONSIGNMENT_FACT.PERSONEEL_ID = PERSONEEL_DIM.PERSONEEL_ID
INNER JOIN TIME_DIM ON CONSIGNMENT_FACT.SCHED_TIME_ID = TIME_DIM.TIME_ID
INNER JOIN WEATHER_DIM ON CONSIGNMENT_FACT.WEATHER_ID = WEATHER_DIM.WEATHER_ID
where WEATHER_DIM.WEATHER_ID = 1
GROUP BY MAAND, JAAR

USE anbc_ster
SELECT SUM(AANTAL) as aantalBezorgingenbijgoedweer
FROM CONSIGNMENT_FACT
INNER JOIN PERSONEEL_DIM ON CONSIGNMENT_FACT.PERSONEEL_ID = PERSONEEL_DIM.PERSONEEL_ID
INNER JOIN TIME_DIM ON CONSIGNMENT_FACT.SCHED_TIME_ID = TIME_DIM.TIME_ID
INNER JOIN WEATHER_DIM ON CONSIGNMENT_FACT.WEATHER_ID = WEATHER_DIM.WEATHER_ID
where WEATHER_DIM.WEATHER_ID = 0
GROUP BY MAAND, JAAR





